// <auto-generated />
namespace leverage_jay_demo_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeimage));
        
        string IMigrationMetadata.Id
        {
            get { return "201511110823551_changeimage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
